version: "3"

services:
  frontend:
    image: mifrontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 9000:3000
    environment:
      - SERVICE_BACKEND1=http://localhost:9010
      - PORT=3000
    networks:
      - mired

networks:
  mired:
