apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  labels:
    app: backend1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
        - name: backend1-pod
          image: gcr.io/cursok8s-306121/mibackend1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3010
          env:
            - name: SERVICE_BACKEND2
              value: http://backend2-svc
            - name: PORT
              value: "3010"
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3010
            initialDelaySeconds: 20
            periodSeconds: 1800
