apiVersion: v1
kind: Pod
metadata:
  name: serverweb6
  labels:
    app: front
    env: dev
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: serverweb7
  labels:
    app: back
    env: dev
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
